# Generated by Django 4.2.16 on 2024-10-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='is_editor',
            field=models.BooleanField(default=False),
        ),
    ]
