# Generated by Django 4.2.16 on 2024-10-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_edited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('queued', 'Queued'), ('published', 'Published')], default='inactive', max_length=20),
        ),
    ]
